"""Adiciona tabela usuariosPreferencias

Revision ID: 1c9c277f6a15
Revises: a69eeaf2101d
Create Date: 2024-11-29 17:03:48.995289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9c277f6a15'
down_revision = 'a69eeaf2101d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuariosPreferencias',
    sa.Column('preferenciaId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('preferenciaTema', sa.String(length=30), nullable=False),
    sa.Column('preferenciaPosicaoBotoes', sa.JSON(), nullable=True),
    sa.Column('preferenciaMiniAppsHome', sa.JSON(), nullable=True),
    sa.Column('preferenciaDataCadastro', sa.DateTime(), nullable=True),
    sa.Column('preferenciaDataUltimaAtualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.usuarioId'], ),
    sa.PrimaryKeyConstraint('preferenciaId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuariosPreferencias')
    # ### end Alembic commands ###
