"""Add usuariosPermissoes table

Revision ID: 4cc0c9859f7f
Revises: 8740c2ed0eb8
Create Date: 2024-11-27 21:11:33.128684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc0c9859f7f'
down_revision = '8740c2ed0eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuariosPermissoes',
    sa.Column('permissaoId', sa.Integer(), nullable=False),
    sa.Column('statusId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('miniAppId', sa.Integer(), nullable=False),
    sa.Column('permissaoMotivo', sa.String(length=255), nullable=True),
    sa.Column('permissaoDataCadastro', sa.DateTime(), nullable=True),
    sa.Column('permissaoDataUltimaAtualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['miniAppId'], ['miniApps.miniAppId'], ),
    sa.ForeignKeyConstraint(['statusId'], ['status.statusId'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.usuarioId'], ),
    sa.PrimaryKeyConstraint('permissaoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuariosPermissoes')
    # ### end Alembic commands ###
