"""Adiciona campo miniAppLink com nullable=True

Revision ID: 79a036b8e69c
Revises: 77e8f28fcfab
Create Date: 2024-11-28 15:20:56.734777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a036b8e69c'
down_revision = '77e8f28fcfab'
branch_labels = None
depends_on = None


def upgrade():
    # Ajuste na tabela 'menus'
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.alter_column(
            'menuTemplate',
            existing_type=sa.VARCHAR(length=50),
            nullable=False
        )
        # Adicionando um nome explícito para a restrição de unicidade
        batch_op.create_unique_constraint('uq_menuTemplate', ['menuTemplate'])

    # Ajuste na tabela 'miniApps'
    with op.batch_alter_table('miniApps', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('miniAppLink', sa.String(length=200), nullable=True)
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniApps', schema=None) as batch_op:
        batch_op.drop_column('miniAppLink')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('menuTemplate',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
