"""Criação da tabela menus

Revision ID: 8740c2ed0eb8
Revises: 
Create Date: 2024-11-27 15:09:37.153189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8740c2ed0eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('menuId', sa.Integer(), nullable=False),
    sa.Column('menuNome', sa.String(length=30), nullable=False),
    sa.Column('menuDataCadastro', sa.DateTime(), nullable=True),
    sa.Column('menuDataUltimaAtualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('menuId'),
    sa.UniqueConstraint('menuNome')
    )
    op.create_table('miniApps',
    sa.Column('miniAppId', sa.Integer(), nullable=False),
    sa.Column('miniAppNome', sa.String(length=100), nullable=False),
    sa.Column('miniAppIcon', sa.String(length=40), nullable=False),
    sa.Column('menuId', sa.Integer(), nullable=False),
    sa.Column('miniAppDataCadastro', sa.DateTime(), nullable=True),
    sa.Column('miniAppDataUltimaAtualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['menuId'], ['menus.menuId'], ),
    sa.PrimaryKeyConstraint('miniAppId'),
    sa.UniqueConstraint('miniAppNome')
    )
    op.create_table('perfisPermissoes',
    sa.Column('perfilPermissaoId', sa.Integer(), nullable=False),
    sa.Column('perfilId', sa.Integer(), nullable=False),
    sa.Column('miniAppId', sa.Integer(), nullable=False),
    sa.Column('perfilPermissaoDataCadastro', sa.DateTime(), nullable=True),
    sa.Column('perfilPermissaoDataUltimaAtualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['miniAppId'], ['miniApps.miniAppId'], ),
    sa.ForeignKeyConstraint(['perfilId'], ['usuariosPerfis.perfilId'], ),
    sa.PrimaryKeyConstraint('perfilPermissaoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfisPermissoes')
    op.drop_table('miniApps')
    op.drop_table('menus')
    # ### end Alembic commands ###
