"""Criação da tabela usuariosLogs

Revision ID: a69eeaf2101d
Revises: e0708ee951d7
Create Date: 2024-11-29 08:58:10.597487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69eeaf2101d'
down_revision = 'e0708ee951d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuariosLogs',
    sa.Column('logId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('logTimestamp', sa.DateTime(), nullable=False),
    sa.Column('miniAppId', sa.Integer(), nullable=True),
    sa.Column('logAcao', sa.String(length=255), nullable=False),
    sa.Column('logResultadoAcao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['miniAppId'], ['miniApps.miniAppId'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.usuarioId'], ),
    sa.PrimaryKeyConstraint('logId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuariosLogs')
    # ### end Alembic commands ###
