"""Torna o campo miniAppLink obrigatório

Revision ID: e0708ee951d7
Revises: 79a036b8e69c
Create Date: 2024-11-29 08:46:06.597096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0708ee951d7'
down_revision = '79a036b8e69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniApps', schema=None) as batch_op:
        batch_op.alter_column('miniAppLink',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miniApps', schema=None) as batch_op:
        batch_op.alter_column('miniAppLink',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
